In [1]:
saleDF = spark.read.csv('wasb:///AUCTION_SALE_PRICE.csv', header=True, inferSchema=True)

Starting Spark application

SparkSession available as 'spark'.

In [2]:
saleDF.count()

1000

In [3]:
vinDF = spark.read.csv('wasb:///VIN_LOOKUP.csv', header =True , inferSchema = True)
groundedDF = spark.read.csv('wasb:///GROUNDED_VEHICLES.csv', header = True, inferSchema = True)

In [4]:
vinDF.count()

1000

In [5]:
groundedDF.count()

1000

In [9]:
saleDF.take(5)

[Row(vin_810=u'1G6DP5E3C', sale_price=26401.1088), Row(vin_810=u'1G6DP5E3D', sale_price=14184.12512), Row(vin_810=u'1G6DP5E3D', sale_price=10872.59008), Row(vin_810=u'1G6DP5E3D', sale_price=13367.44464), Row(vin_810=u'1G6DP5E3D', sale_price=25098.82408)]

In [7]:
vinDF.take(5)

[Row(vin=u'1G6DP5E39C0107021', make=u'Cadillac', model=u'CTS Sedan', year=2012, base_msrp_high=48290), Row(vin=u'1G6DP5E39D0101219', make=u'Cadillac', model=u'CTS Sedan', year=2013, base_msrp_high=48290), Row(vin=u'1G6DP5E39D0162201', make=u'Cadillac', model=u'CTS Sedan', year=2013, base_msrp_high=48290), Row(vin=u'1G6DP5E39D0163610', make=u'Cadillac', model=u'CTS Sedan', year=2013, base_msrp_high=48290), Row(vin=u'1G6DP5E39D0180052', make=u'Cadillac', model=u'CTS Sedan', year=2013, base_msrp_high=48290)]

In [8]:
groundedDF.take(5)

[Row(vin=u'1G6DP5E39C0107021', odometer_reading=48340), Row(vin=u'1G6DP5E39D0101219', odometer_reading=19216), Row(vin=u'1G6DP5E39D0162201', odometer_reading=10644), Row(vin=u'1G6DP5E39D0163610', odometer_reading=17102), Row(vin=u'1G6DP5E39D0180052', odometer_reading=47469)]

In [15]:
saleDF.createTempView('saleDF')
vinDF.createTempView('vinDF')
groundedDF.createTempView('groundedDF')

In [27]:
df_1 = saleDF.join(vinDF, saleDF.vin_810 == vinDF.vin, how = 'full')
df_1.take(5)

[Row(vin_810=u'1G6DS1EDB', sale_price=16904.84064, vin=None, make=None, model=None, year=None, base_msrp_high=None), Row(vin_810=u'1G6DS1EDB', sale_price=13284.84432, vin=None, make=None, model=None, year=None, base_msrp_high=None), Row(vin_810=u'1G6DS1EDB', sale_price=16017.7176, vin=None, make=None, model=None, year=None, base_msrp_high=None), Row(vin_810=u'1G6DS1EDB', sale_price=18374.60472, vin=None, make=None, model=None, year=None, base_msrp_high=None), Row(vin_810=u'1G6DS1EDB', sale_price=15664.1256, vin=None, make=None, model=None, year=None, base_msrp_high=None)]

In [28]:
fullDF = df_1.join(groundedDF, df_1.vin == groundedDF.vin, how = 'full')
fullDF.take(5)

[Row(vin_810=None, sale_price=None, vin=None, make=None, model=None, year=None, base_msrp_high=None, vin=u'1G6DP5ED5B0138595', odometer_reading=26749), Row(vin_810=None, sale_price=None, vin=None, make=None, model=None, year=None, base_msrp_high=None, vin=u'1G6DS1E38C0125999', odometer_reading=35237), Row(vin_810=None, sale_price=None, vin=None, make=None, model=None, year=None, base_msrp_high=None, vin=u'1G6DS1ED1B0171469', odometer_reading=34854), Row(vin_810=None, sale_price=None, vin=None, make=None, model=None, year=None, base_msrp_high=None, vin=u'1G6DS5E38C0112242', odometer_reading=31310), Row(vin_810=None, sale_price=None, vin=None, make=None, model=None, year=None, base_msrp_high=None, vin=u'1G6DS5E3XC0112680', odometer_reading=50487)]

In [29]:
fullDF.count()

2000